AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FirstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  VPC02:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
